# Translations template for PROJECT.
# Copyright (C) 2022 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2022.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2022-10-31 10:52+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.10.3\n"

#: launch_worker.py:47
msgid "FILE_UPLOADED"
msgstr ""

#: src/backend/verifier_exports.py:76 src/backend/verifier_exports.py:79
msgid "XML_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr ""

#: src/backend/verifier_exports.py:163 src/backend/verifier_exports.py:166
msgid "PDF_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr ""

#: src/backend/controllers/splitter.py:282
#: src/backend/controllers/splitter.py:288 src/backend/verifier_exports.py:318
#: src/backend/verifier_exports.py:324 src/backend/verifier_exports.py:330
msgid "EXPORT_MAARCH_ERROR"
msgstr ""

#: src/backend/verifier_exports.py:325
msgid "PDF_FILE_NOT_FOUND"
msgstr ""

#: src/backend/verifier_exports.py:336
msgid "MAARCH_WS_INFO_WRONG"
msgstr ""

#: src/backend/controllers/splitter.py:294 src/backend/verifier_exports.py:342
msgid "MAARCH_WS_INFO_EMPTY"
msgstr ""

#: src/backend/classes/MaarchWebServices.py:38
msgid "HOST_NOT_FOUND"
msgstr ""

#: src/backend/controllers/accounts.py:46 src/backend/models/accounts.py:55
msgid "GET_SUPPLIER_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:59 src/backend/models/accounts.py:75
msgid "GET_ADDRESS_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:80
#: src/backend/controllers/accounts.py:159
msgid "UPDATE_SUPPLIER_POSITIONS_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:101
#: src/backend/controllers/accounts.py:190
msgid "UPDATE_SUPPLIER_PAGES_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:122
#: src/backend/controllers/accounts.py:128
msgid "UPDATE_SUPPLIER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:214
#: src/backend/controllers/accounts.py:220
#: src/backend/controllers/accounts.py:244
#: src/backend/controllers/accounts.py:250 src/backend/models/accounts.py:115
msgid "UPDATE_ADDRESS_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:274 src/backend/models/accounts.py:132
msgid "CREATE_ADDRESS_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:311
#: src/backend/controllers/accounts.py:317 src/backend/models/accounts.py:149
msgid "CREATE_SUPPLIER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:318
msgid "SUPPLIER_VAT_NUMBER_ALREADY_EXISTS"
msgstr ""

#: src/backend/controllers/accounts.py:338 src/backend/controllers/user.py:118
#: src/backend/models/accounts.py:204 src/backend/models/accounts.py:224
#: src/backend/models/accounts.py:240 src/backend/models/user.py:162
msgid "GET_CUSTOMER_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:378
#: src/backend/controllers/accounts.py:384 src/backend/models/accounts.py:259
msgid "UPDATE_CUSTOMER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:412
#: src/backend/controllers/accounts.py:418 src/backend/models/accounts.py:276
msgid "CREATE_CUSTOMER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:419
msgid "CUSTOMER_VAT_NUMBER_ALREADY_EXISTS"
msgstr ""

#: src/backend/controllers/accounts.py:433
#: src/backend/controllers/accounts.py:439 src/backend/models/accounts.py:295
msgid "DELETE_CUSTOMER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:454
#: src/backend/controllers/accounts.py:460 src/backend/models/accounts.py:168
msgid "DELETE_SUPPLIER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:484
msgid "LOAD_SUPPLIER_REFERENCIAL_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:58 src/backend/controllers/auth.py:97
#: src/backend/controllers/auth.py:139 src/backend/controllers/auth.py:183
#: src/backend/controllers/auth.py:194 src/backend/controllers/auth.py:204
#: src/backend/controllers/auth.py:231 src/backend/rest/auth.py:99
msgid "LOGIN_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:115 src/backend/controllers/auth.py:154
#: src/backend/controllers/auth.py:162 src/backend/controllers/auth.py:164
msgid "JWT_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:195
msgid "SEVERAL_AUTH_METHODS_ENABLED"
msgstr ""

#: src/backend/controllers/auth.py:219
msgid "LDAP_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:220 src/backend/models/auth.py:125
msgid "NO_LDAP_CONFIGURATIONS_FOUND"
msgstr ""

#: src/backend/controllers/auth.py:246
msgid "LOADING_METHODS_AUTH_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:258
msgid "DISABLE_LOGIN_METHOD_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:270
msgid "ENABLE_LOGIN_METHOD_ERROR"
msgstr ""

#: src/backend/controllers/config.py:62
msgid "RETRIEVE_CONFIGURATION_ERRORS"
msgstr ""

#: src/backend/controllers/config.py:78
msgid "RETRIEVE_CONFIGURATIONS_ERRORS"
msgstr ""

#: src/backend/controllers/config.py:94
msgid "RETRIEVE_DOCSERVERS_ERRORS"
msgstr ""

#: src/backend/controllers/config.py:110
msgid "RETRIEVE_REGEX_ERRORS"
msgstr ""

#: src/backend/controllers/config.py:122 src/backend/controllers/config.py:142
#: src/backend/models/config.py:157
msgid "UPDATE_CONFIGURATION_ERROR"
msgstr ""

#: src/backend/controllers/config.py:123
msgid "JWT_EXPIRATION_COULDNT_BE_ZERO_OR_LESS"
msgstr ""

#: src/backend/controllers/config.py:163 src/backend/models/config.py:176
msgid "UPDATE_REGEX_ERROR"
msgstr ""

#: src/backend/controllers/config.py:183 src/backend/models/config.py:199
msgid "UPDATE_DOCSERVER_ERROR"
msgstr ""

#: src/backend/controllers/config.py:224 src/backend/controllers/config.py:234
#: src/backend/controllers/config.py:239
msgid "ERROR_UPDATING_IMAGE"
msgstr ""

#: src/backend/controllers/config.py:225 src/backend/controllers/config.py:235
msgid "CUSTOM_IMAGE_PATH_NOT_WRITEABLE_OR_NOT_EXISTS"
msgstr ""

#: src/backend/controllers/config.py:240
msgid "CUSTOM_NOT_PRESENT"
msgstr ""

#: src/backend/controllers/custom_fields.py:32
#: src/backend/controllers/custom_fields.py:48
#: src/backend/controllers/custom_fields.py:61
msgid "CUSTOM_FIELDS_ERROR"
msgstr ""

#: src/backend/controllers/custom_fields.py:74
msgid "CUSTOM_FIELDS_DELETE_ERROR"
msgstr ""

#: src/backend/controllers/doctypes.py:35
#: src/backend/controllers/doctypes.py:77 src/backend/models/doctypes.py:119
#: src/backend/models/doctypes.py:122
msgid "SET_DEFAULT_DOCTYPE_ERROR"
msgstr ""

#: src/backend/controllers/doctypes.py:41 src/backend/models/doctypes.py:48
msgid "ADD_DOCTYPE_ERROR"
msgstr ""

#: src/backend/controllers/doctypes.py:61
#: src/backend/controllers/doctypes.py:97
#: src/backend/controllers/doctypes.py:110
#: src/backend/controllers/doctypes.py:142
#: src/backend/controllers/doctypes.py:171
msgid "DOCTYPE_ERROR"
msgstr ""

#: src/backend/controllers/doctypes.py:130
msgid "DOCTYPESEPARATOR"
msgstr ""

#: src/backend/controllers/doctypes.py:133
msgid "DOCUMENTSEPARATOR"
msgstr ""

#: src/backend/controllers/doctypes.py:136
msgid "BUNDLESEPARATOR"
msgstr ""

#: src/backend/controllers/forms.py:41 src/backend/controllers/forms.py:51
#: src/backend/controllers/forms.py:77 src/backend/controllers/forms.py:185
msgid "FORMS_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:92 src/backend/controllers/forms.py:141
#: src/backend/models/forms.py:57
msgid "GET_FORM_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:124
msgid "GET_FORM_FIELDS_BY_FORM_ID_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:179 src/backend/controllers/forms.py:307
#: src/backend/controllers/forms.py:313
msgid "UPDATE_FORMS_FIELDS_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:199 src/backend/controllers/forms.py:205
msgid "DELETE_FORM_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:214 src/backend/controllers/inputs.py:66
#: src/backend/controllers/outputs.py:54
#: src/backend/controllers/positions_masks.py:159
msgid "COPY_OF"
msgstr ""

#: src/backend/controllers/forms.py:231 src/backend/controllers/forms.py:237
msgid "DUPLICATE_FORM_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:251 src/backend/controllers/forms.py:257
msgid "DISABLE_FORM_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:271 src/backend/controllers/forms.py:277
msgid "ENABLE_FORM_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:293
msgid "GET_FORMS_FIELDS_ERROR"
msgstr ""

#: src/backend/controllers/history.py:28
msgid "ADD_HISTORY_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:48 src/backend/controllers/inputs.py:54
msgid "UPDATE_INPUT_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:79 src/backend/controllers/inputs.py:85
msgid "DUPLICATE_INPUT_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:110 src/backend/controllers/inputs.py:121
#: src/backend/controllers/inputs.py:134
msgid "CREATE_INPUT_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:111
msgid "INPUT_ID_ALREADY_EXISTS"
msgstr ""

#: src/backend/controllers/inputs.py:122
msgid "INPUT_FOLDER_ALREADY_EXISTS"
msgstr ""

#: src/backend/controllers/inputs.py:147
msgid "GET_INPUT_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:168 src/backend/controllers/inputs.py:174
msgid "DELETE_INPUT_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:210
msgid "FS_WATCHER_DELETION_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:211 src/backend/controllers/inputs.py:278
msgid "FS_WATCHER_CONFIG_DOESNT_EXIST"
msgstr ""

#: src/backend/controllers/inputs.py:257 src/backend/controllers/inputs.py:277
msgid "FS_WATCHER_CREATION_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:258
msgid "CAN_NOT_CREATE_FOLDER_PERMISSION_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:283
msgid "SCRIPT_SAMPLE_DOESNT_EXISTS"
msgstr ""

#: src/backend/controllers/inputs.py:289
msgid "SCRIPT_FOLDER_DOESNT_EXISTS"
msgstr ""

#: src/backend/controllers/mailcollect.py:36
msgid "RETRIEVE_PROCESSES_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:52
msgid "UPDATE_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:68
msgid "CREATE_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:82
#: src/backend/controllers/mailcollect.py:88
msgid "DELETE_MAILCOLLECT_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:102
#: src/backend/controllers/mailcollect.py:108
msgid "ENABLE_MAILCOLLECT_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:122
#: src/backend/controllers/mailcollect.py:128
msgid "DISABLE_MAILCOLLECT_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:142
#: src/backend/controllers/mailcollect.py:152
msgid "MAILCOLLECT_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:61 src/backend/controllers/outputs.py:67
msgid "DUPLICATE_OUTPUT_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:92 src/backend/controllers/outputs.py:98
msgid "UPDATE_OUTPUT_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:122
msgid "CREATE_OUTPUT_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:135
msgid "GET_OUTPUT_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:148
msgid "GET_OUTPUT_TYPE_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:162
#: src/backend/controllers/outputs.py:168
msgid "DELETE_OUTPUT_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:42
#: src/backend/controllers/positions_masks.py:62
#: src/backend/controllers/positions_masks.py:117
#: src/backend/controllers/positions_masks.py:123
msgid "POSITION_MASKS_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:77
#: src/backend/controllers/positions_masks.py:94
msgid "GET_POSITION_MASK_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:141
#: src/backend/controllers/positions_masks.py:147
msgid "DELETE_POSITION_MASK_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:175
#: src/backend/controllers/positions_masks.py:181
msgid "DUPLICATE_POSITIONS_MASKS_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:199
#: src/backend/controllers/positions_masks.py:205
msgid "DISABLE_POSITION_MASK_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:223
#: src/backend/controllers/positions_masks.py:229
msgid "ENABLE_POSITION_MASK_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:255
msgid "UPDATE_POSITIONS_BY_POSITIONS_MASK_ID_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:281
msgid "UPDATE_PAGES_BY_POSITIONS_MASK_ID_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:302
msgid "DELETE_POSITIONS_BY_POSITION_MASK_ID_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:323
msgid "DELETE_PAGES_BY_POSITION_MASK_ID_ERROR"
msgstr ""

#: src/backend/controllers/privileges.py:37
#: src/backend/controllers/privileges.py:65
msgid "GET_PRIVILEGES_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:47 src/backend/controllers/roles.py:53
#: src/backend/controllers/roles.py:95 src/backend/controllers/roles.py:101
#: src/backend/models/roles.py:75
msgid "UPDATE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:75 src/backend/models/roles.py:92
msgid "CREATE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:114
msgid "GET_ROLE_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:128 src/backend/controllers/roles.py:134
msgid "DELETE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:148 src/backend/controllers/roles.py:154
msgid "DISABLE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:168 src/backend/controllers/roles.py:174
msgid "ENABLE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:84
msgid "LOAD_METADATA_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:112
#: src/backend/controllers/verifier.py:75
msgid "AT"
msgstr ""

#: src/backend/controllers/splitter.py:134
msgid "FORM_UNDEFINED"
msgstr ""

#: src/backend/controllers/splitter.py:231
msgid "ADD_DOCUMENT_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:350
#: src/backend/controllers/splitter.py:595
msgid "EXPORT_PDF_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:372
#: src/backend/controllers/splitter.py:619
msgid "EXPORT_XML_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:388
msgid "UPDATE_BATCH_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:400
msgid "UPDATE_DOCUMENTS_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:413
msgid "UPDATE_DOCUMENT_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:428
#: src/backend/controllers/splitter.py:449
#: src/backend/controllers/splitter.py:464
#: src/backend/controllers/splitter.py:479
msgid "UPDATE_PAGES_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:493
msgid "CMIS_CONNECTION_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:717
#: src/backend/controllers/verifier.py:557 src/backend/models/splitter.py:423
#: src/backend/models/verifier.py:153
msgid "GET_TOTALS_ERROR"
msgstr ""

#: src/backend/controllers/status.py:31
msgid "RETRIEVES_STATUS_ERROR"
msgstr ""

#: src/backend/controllers/tasks_watcher.py:34
msgid "CREATE_TASK_ERROR"
msgstr ""

#: src/backend/controllers/user.py:33
msgid "CREATE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:71 src/backend/models/user.py:121
#: src/backend/models/user.py:142
msgid "GET_USER_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/user.py:88
msgid "GET_USER_BY_USERNAME_ERROR"
msgstr ""

#: src/backend/controllers/user.py:134
msgid "UPDATE_PROFILE"
msgstr ""

#: src/backend/controllers/user.py:135
msgid "ERROR_OLD_PASSWORD_NOT_MATCH"
msgstr ""

#: src/backend/controllers/user.py:140
msgid "UPDATE_USER"
msgstr ""

#: src/backend/controllers/user.py:141
msgid "ERROR_PASSWORD_NOT_MATCH"
msgstr ""

#: src/backend/controllers/user.py:167 src/backend/controllers/user.py:173
#: src/backend/models/user.py:182
msgid "UPDATE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:187 src/backend/controllers/user.py:193
msgid "DELETE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:207 src/backend/controllers/user.py:213
msgid "DISABLE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:227 src/backend/controllers/user.py:233
msgid "ENABLE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:250 src/backend/controllers/user.py:256
#: src/backend/models/user.py:201
msgid "UPDATE_CUSTOMERS_USER_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:56 src/backend/models/verifier.py:37
msgid "GET_INVOICE_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:167
#: src/backend/controllers/verifier.py:269
msgid "UPDATE_INVOICE_POSITIONS_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:190
#: src/backend/controllers/verifier.py:287
msgid "UPDATE_INVOICE_PAGES_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:213
#: src/backend/controllers/verifier.py:231
msgid "UPDATE_INVOICE_DATA_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:301
#: src/backend/controllers/verifier.py:307
msgid "DELETE_INVOICE_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:322
#: src/backend/controllers/verifier.py:328
msgid "UPDATE_INVOICE_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:345
msgid "REMOVE_LOCK_BY_USER_ID_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:465
#: src/backend/controllers/verifier.py:468
#: src/backend/controllers/verifier.py:485
#: src/backend/controllers/verifier.py:504
#: src/backend/controllers/verifier.py:505
msgid "API_INSEE_ERROR_CONNEXION"
msgstr ""

#: src/backend/controllers/verifier.py:529
msgid "VAT_NOT_VALID"
msgstr ""

#: src/backend/controllers/verifier.py:534
#: src/backend/controllers/verifier.py:535
msgid "VAT_API_ERROR"
msgstr ""

#: src/backend/models/accounts.py:96
msgid "SUPPLIER_UPDATE_ERROR"
msgstr ""

#: src/backend/models/auth.py:40 src/backend/models/auth.py:92
#: src/backend/models/user.py:40 src/backend/rest/auth.py:100
msgid "BAD_USERNAME"
msgstr ""

#: src/backend/models/auth.py:42 src/backend/models/user.py:42
msgid "BAD_PASSWORD"
msgstr ""

#: src/backend/models/auth.py:44
msgid "USER_DELETED"
msgstr ""

#: src/backend/models/auth.py:46
msgid "USER_DISABLED"
msgstr ""

#: src/backend/models/auth.py:64 src/backend/models/auth.py:74
#: src/backend/models/roles.py:54
msgid "ROLE_DOESNT_EXISTS"
msgstr ""

#: src/backend/models/auth.py:147
msgid "UPDATE_LOGIN_METHOD_ERROR"
msgstr ""

#: src/backend/models/auth.py:187
msgid "DISABLE_LOGIN_METHOD_DATA_ERROR"
msgstr ""

#: src/backend/models/auth.py:206
msgid "ENABLE_LOGIN_METHOD_DATA_ERROR"
msgstr ""

#: src/backend/models/custom_fields.py:52
msgid "ADD_CUSTOM_FIELD_ERROR"
msgstr ""

#: src/backend/models/custom_fields.py:55
msgid "CUSTOM_FIELD_ALREADY_EXIST"
msgstr ""

#: src/backend/models/custom_fields.py:98
msgid "UPDATE_CUSTOM_FIELDS_ERROR"
msgstr ""

#: src/backend/models/custom_fields.py:118
msgid "DELETE_CUSTOM_FIELDS_ERROR"
msgstr ""

#: src/backend/models/doctypes.py:51
msgid "DOCTYPE_ALREADY_EXIST"
msgstr ""

#: src/backend/models/doctypes.py:91
msgid "UPDATE_DOCTYPE_ERROR"
msgstr ""

#: src/backend/models/forms.py:77
msgid "GET_FORM_SETTINGS_BY_ID_ERROR"
msgstr ""

#: src/backend/models/forms.py:97
msgid "GET_DEFAULT_FORM_ERROR"
msgstr ""

#: src/backend/models/forms.py:118
msgid "UPDATE_FORM_ERROR"
msgstr ""

#: src/backend/models/forms.py:137
msgid "UPDATE_FORM_FIELDS_ERROR"
msgstr ""

#: src/backend/models/forms.py:187
msgid "ADD_FORM_ERROR"
msgstr ""

#: src/backend/models/forms.py:190
msgid "FORM_LABEL_ALREADY_EXIST"
msgstr ""

#: src/backend/models/inputs.py:54
msgid "INPUT_DOESNT_EXISTS"
msgstr ""

#: src/backend/models/inputs.py:90
msgid "INPUT_UPDATE_ERROR"
msgstr ""

#: src/backend/models/inputs.py:107
msgid "INPUT_CREATE_ERROR"
msgstr ""

#: src/backend/models/mailcollect.py:76
msgid "MAILCOLLECT_PROCESS_UPDATE_ERROR"
msgstr ""

#: src/backend/models/outputs.py:69
msgid "OUTPUT_DOESNT_EXISTS"
msgstr ""

#: src/backend/models/outputs.py:89
msgid "OUTPUT_TYPE_DOESNT_EXISTS"
msgstr ""

#: src/backend/models/outputs.py:110
msgid "OUTPUT_UPDATE_ERROR"
msgstr ""

#: src/backend/models/outputs.py:127
msgid "OUTPUT_CREATE_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:57
msgid "GET_POSITIONS_MASKS_BY_ID_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:78
msgid "UPDATE_POSITIONS_MASKS_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:97
msgid "UPDATE_POSITIONS_MASKS_FIELDS_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:129
msgid "ADD_POSITIONS_MASKS_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:132
msgid "POSITIONS_MASK_LABEL_ALREADY_EXIST"
msgstr ""

#: src/backend/models/privileges.py:35 src/backend/models/privileges.py:53
msgid "ERROR_RETRIEVING_PRIVILEGES"
msgstr ""

#: src/backend/models/roles.py:111
msgid "ROLE_PRIVILEGES_UPDATE_ERROR"
msgstr ""

#: src/backend/models/roles.py:130
msgid "ROLE_PRIVILEGES_CREATE_ERROR"
msgstr ""

#: src/backend/models/splitter.py:69
msgid "GET_MAX_SPLIT_INDEX_ERROR"
msgstr ""

#: src/backend/models/splitter.py:110
msgid "UPDATE_SETTINGS_ERROR"
msgstr ""

#: src/backend/models/splitter.py:132
msgid "INSERT_PAGE_ERROR"
msgstr ""

#: src/backend/models/splitter.py:193
msgid "GET_BATCH_ERROR"
msgstr ""

#: src/backend/models/splitter.py:213
msgid "GET_DOCUMENTS_ERROR"
msgstr ""

#: src/backend/models/splitter.py:233
msgid "GET_PAGES_ERROR"
msgstr ""

#: src/backend/models/splitter.py:252
msgid "GET_MAX_SOURCE_PAGE_VALUE_ERROR"
msgstr ""

#: src/backend/models/splitter.py:272
msgid "GET_DOCUMENT_ERROR"
msgstr ""

#: src/backend/models/splitter.py:291
msgid "GET_DOCUMENT_MAX_SPLIT_INDEX_ERROR"
msgstr ""

#: src/backend/models/status.py:37
msgid "NO_STATUS"
msgstr ""

#: src/backend/models/tasks_watcher.py:72
msgid "UPDATE_TASK_ERROR"
msgstr ""

#: src/backend/models/user.py:44
msgid "USER"
msgstr ""

#: src/backend/models/user.py:44
msgid "ALREADY_REGISTERED"
msgstr ""

#: src/backend/models/verifier.py:92 src/backend/models/verifier.py:110
msgid "INVOICE_UPDATE_ERROR"
msgstr ""

#: src/backend/rest/auth.py:53 src/backend/rest/auth.py:104
msgid "PGSQL_ERROR"
msgstr ""

#: src/backend/rest/auth.py:89 src/backend/rest/auth.py:254
#: src/backend/rest/auth.py:268 src/backend/rest/auth.py:277
#: src/backend/rest/auth.py:282 src/backend/rest/auth.py:472
msgid "LDAP_CONNECTION_ERROR"
msgstr ""

#: src/backend/rest/auth.py:90
msgid "LOGIN_LDAP_ERROR"
msgstr ""

#: src/backend/rest/auth.py:252 src/backend/rest/auth.py:266
#: src/backend/rest/auth.py:275
msgid "BAD_CONNECTION_LDAP_INFOS"
msgstr ""

#: src/backend/rest/auth.py:286
msgid "NOT_COMPLETE_CONNECTION_INFOS"
msgstr ""

#: src/backend/rest/auth.py:288 src/backend/rest/auth.py:477
#: src/backend/rest/auth.py:483
msgid "INFOS_LDAP_NOT_COMPLETE"
msgstr ""

#: src/backend/rest/auth.py:460 src/backend/rest/auth.py:465
#: src/backend/rest/auth.py:471 src/backend/rest/auth.py:476
#: src/backend/rest/auth.py:482
msgid "LDAP_SYNCHRO_ERROR"
msgstr ""

#: src/backend/rest/auth.py:461 src/backend/rest/auth.py:466
msgid "LDAP_SYNCHRO_INFOS_ERROR"
msgstr ""

#: src/backend/rest/auth.py:495 src/backend/rest/auth.py:522
#: src/backend/rest/auth.py:536
msgid "REQUEST_MODIFS_ERROR"
msgstr ""

#: src/backend/rest/auth.py:508
msgid "RETRIEVE_LOGIN_METHODS_ERROR"
msgstr ""

#: src/backend/rest/splitter.py:38 src/backend/rest/verifier.py:37
msgid "UNKNOW_ERROR"
msgstr ""

